name: JodelleSimpleSpawn
version: 25.22
main: org.jodellesimplespawn.jodelleSimpleSpawn.JodelleSimpleSpawn
commands:
  jsp:
    description: Set the spawn location to your current position
    usage: /jsp setspawn
permissions:
  jodellesimplespawn.setspawn:
    description: Allows setting the spawn location
    default: op
